### ISSUE TITLE
capital letter and under score are not allowed as bucket title in AWS s3

### ISSUE THREAD

**Issue by photoszzt** [excamera/pipeline#2]
https://github.com/excamera/pipeline/blob/d1b3190ec859825465a33b3155db7a6f484e4c04/sprocket/util/misc.py#L16-L28

rand_str will return the capital letter, but capital letter is not permitted by AWS as bucket name : https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by photoszzt** [comment]
I modify the function to something like this:

```python
def rand_str(slen):
    import string
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(slen))
```

**Comment by lihshyang** [comment]
Fixed. Thanks!
