### ISSUE TITLE
mpd file only contains the first segment

### ISSUE THREAD

**Issue by photoszzt** [excamera/pipeline#3]
The mpd file only contains the first segment in the segment list. But to play the whole video, the mpd file should contain all the segments generated.

**Comment by lihshyang** [comment]
Can you post the detailed pipeline_daemon logs (in debug mode)?

**Comment by photoszzt** [comment]
[log.txt](https://github.com/excamera/pipeline/files/3219183/log.txt)
The debug log file is attached above.

**Comment by lihshyang** [comment]
Seems [sprocket/util/amend_mpd.py](https://github.com/excamera/pipeline/blob/f7ab4336375eb72d3c077b7150cfb2cce7592583/sprocket/util/amend_mpd.py) wasn't working as expected.

This function convert the original 00000001_dash.mpd which contains only the first segment to output.xml which should includes all segments.

Can you also post your 00000001_dash.mpd, which should be in your local logs/20190525065135-3bta/ directory.

**Comment by photoszzt** [comment]
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.7.2-DEV-rev1109-gf9caebfbc-master  at 2019-05-25T06:51:50.208Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M1.000S" maxSegmentDuration="PT0H0M1.000S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>00000001_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M1.000S">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="818" maxFrameRate="24" par="1920:818" lang="und" startWithSAP="1">
   <SegmentList>
    <Initialization sourceURL="00000001_dash_init.mp4"/>
   </SegmentList>
   <Representation id="video" mimeType="video/mp4" codecs="avc3.640028" width="1920" height="818" frameRate="24" sar="1:1" bandwidth="195896">
    <SegmentList timescale="12288" duration="12288">
     <SegmentURL media="seg_00000001_1.m4s"/>
    </SegmentList>
   </Representation>
   <Representation id="audio" mimeType="video/mp4" codecs="avc3.640028" width="1920" height="818" frameRate="24" sar="1:1" bandwidth="195896">
    <SegmentList timescale="12288" duration="12288">
     <SegmentURL media="seg_00000001_1.m4s"/>
    </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

```

**Comment by lihshyang** [comment]
Interesting. Here it generates a complete segment list for me.

One thing you can try is to debug the amend_mpd function and see where might go wrong.

**Comment by photoszzt** [comment]
I'm looking at that file. The generated output is output.xml and it doesn't replace the mpd file. The player is looking for mpd file not the output.xml.

**Comment by lihshyang** [comment]
I see why it can be confusing here -- the output file is actually output.xml, which is an mpd file. If you look at the pipeline_runner client's output, you'll see it as a returned link. That's the link of the output video.
